### PR TITLE
Add clone functions to urdf classes

### PR DESCRIPTION
**Pull request by chaitanya-deep**

### CODE REVIEW

**Comment by gkjohnson** [comment]
The [Object3D.clone](https://github.com/mrdoob/three.js/blob/dev/src/core/Object3D.js#L845) already handles creating an instance of the original object type so this shouldn't be needed.

```js
	clone: function ( recursive ) {

		return new this.constructor().copy( this, recursive );

	},
```

Were you seeing an issue with the clone function?

**Comment by gkjohnson** [comment]
Was this comment intended for #99? Otherwise I'm not following how the process functions are related to `clone()`.

**Comment by chaitanya-deep** [comment]
Sorry I should've described better.
Previously this was the code to process a urdf joint.
`
jointMap[name] = this._processJoint(j, linkMap);

const obj = new URDFJoint();
obj.urdfNode = joint;
obj.name = joint.getAttribute('name');
obj.jointType = jointType;
`
The change I made in [the branch](https://github.com/rapyuta-robotics/urdf-loaders/tree/feature/process_functions_in_class/javascript/src) would refactor it to this
`
const joint = new URDFJoint(j);
jointMap[joint.name] = joint.process(linkMap);
`
Since in this case since the URDFJoint class takes arguments, the clone functionality would break. To prevent which I had to add a clone function. I chose to make it a separate branch rather than the one with other refactors. It was not evident that there exists a clone function. This PR is to explicitly add an although useless function which could be modified later in other branches that might require such addition.

**Comment by gkjohnson** [comment]
Oh okay I see, now.

I'm not sure if I see the utility or benefit of moving the process function logic over into the respective URDF classes and requiring a node be passed into the constructor. The way I see it the `URDFLoader` class should be responsible for parsing and constructing the model hierarchy while the class instances should be responsible defining the behaviors and fields associated with the link / joint / robot instance. I think I prefer that separation of concerns and would like to keep it that way but I'm open to discussing it. Is there a feature you'd like to enable with this change?

I think I'd like to see the update I suggested in #99 to move the process functions into the parse function which should help clean up a lot data flow complexity. I've made issues #102 and #103 to talk about a couple of these changes if you want to talk about other approaches.

Thanks for laying it out for me!

**Comment by chaitanya-deep** [comment]
The change I intended by moving the process functions to classes is to have everything concerning the urdf link to be in the URDFLink class and similarly for joint and robot.

The link and joint classes are not reusable in the sense that the properties of obj are being set in urdfloader class. For eg, while the name attribute is mandatory for a urdf link, the creation of the link from `URDFLink` class doesn't enforce it. The loader sets it with `obj.name = ''`. Ideally I think the name should be taken in the constructor. 

To facilitate editing the 3d scene while adding and removing links/joints, if I could to use the library to create a new link/joint, having the process functions in the class would mean I could just use `new URDFLink(properties/xml).process()`. The `URDFLink` class in this case will not be tightly coupled with `URDFLoader` class

**Comment by gkjohnson** [comment]
> The link and joint classes are not reusable in the sense that the properties of obj are being set in urdfloader class. For eg, while the name attribute is mandatory for a urdf link, the creation of the link from `URDFLink` class doesn't enforce it.

The classes aren't built or intended to enforce the URDF spec -- just to implement intended behavior. Even with some measures to enforce such things there will always be ways to undermine that, especially with Javascript. I think they are very reusable in the sense that if you want to build up a model shaped like an imported URDF model you can do that and no XML nodes are required. I think any specialized needs for these classes with specific behavior can be implemented and enforced by the containing application.

> The `URDFLink` class in this case will not be tightly coupled with `URDFLoader` class

I don't necessarily agree that the URDFLink class is tightly coupled to the URDFLoader class right now. If you want to create a custom URDFLink instance you're able to instantiate one and modify the fields to behave as desired. I didn't originally intend them to be used in this way but I have thought about exporting them more officially. The loader is only needed if converting an XML URDF file into a THREE.js hierarchy. If anything for editor application using these classes I would expect a "toXML" function to be required, which should be pretty doable.

Do you feel that you're unable to use them or build an editor at the moment with the classes as they are?

**Comment by chaitanya-deep** [comment]
> Do you feel that you're unable to use them or build an editor at the moment with the classes as they are?
At the moment I'm not using the classes for anything. I'm just using the loader. The editing functionality is in the application and very specific for the application. I might try to generalise them later.
I guess this PR can be closed.

**Pull request closed without merging**
