### PR TITLE
support onProgress, onError callbacks on URDFLoader.load

### PR DESCRIPTION
**Pull request by tocttou**
Hi

This PR addresses https://github.com/gkjohnson/urdf-loaders/issues/95

It adds the following callbacks to the `URDFLoader.load` function:

1. `onError(url) => void`: triggered on individual errors for each resource
2. `onProgress(url, itemsLoaded, itemsTotal) => void`: triggered on individual load for each resource
 
Changes to existing functions:

1. `onComplete(model, errors: { [url]: string }) => void`: triggered after all link mesh loads are attempted and either succeed or fail

I have updated the existing tests to pass but have a doubt about writing tests for the above functionality.

Adding new tests seems to modify the `window.model` object that causes other tests to fail. Should I add the new tests at the bottom instead?

Thanks!

### CODE REVIEW

**Comment by gkjohnson** [comment]
Thanks for the contribution! I started this fix in the `options-update` branch:

https://github.com/gkjohnson/urdf-loaders/compare/options-update

but I haven't gotten around to finishing it, yet. My goal was to move the API of URDFLoader to more closely match those of the official [three.js loaders](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/ColladaLoader.js#L56-L70) which means passing `onProgress` and `onError` to the `load` function and moving all the options to class members. I think the other branch more closesly mirrors the way the official loaders work at the moment. I would definitely appreciate some help getting that to the finish line, though! I think at least the tests, docs, and typescript definitions still need to be updated.

> I have updated the existing tests to pass but have a doubt about writing tests for the above functionality.
> 
> Adding new tests seems to modify the window.model object that causes other tests to fail. Should I add the new tests at the bottom instead?

Can you elaborate on what you mean? How does it cause the tests to fail? Maybe we should clear the  `window.model` field in `beforeEach` to ensure everything starts clean?

Thanks again!

**Comment by tocttou** [comment]
Thanks. I got some hint from the `options-update` branch. I'll update that one instead as soon as a I get some time.

> Maybe we should clear the window.model field in beforeEach to ensure everything starts clean?

Yes this appears to be the problem.

**Comment by gkjohnson** [comment]
Great thank you again!

**Comment by unphased** [comment]
Is there an update to this? Handling failures to load urdf resources is difficult now, because throws in the `loadMeshCb` given to URDFLoader will simply be uncaught, and as it's asynchronous, that drops the ball on handling the problem in the rest of the app (which uses React, so there's no clean way to construct a semantic error message for the user).

**Comment by gkjohnson** [comment]
Hey @unphased! There hasn't been a request / need for this in awhile so I haven't put time into it. Do you mind making a new issue so we can discuss it along with a description of how you're using / calling URDFLoader? If it's something you need I'd be happy to help get it in and if you have ideas on how it should be implemented a PR would be great too!

**Pull request closed without merging**
