### PR TITLE
Dev/fetch options

### PR DESCRIPTION
**Pull request by gkjohnson**
Expose the ability to set the fetch options through the `URDFLoader.load` function.

Use cors and same-origin credentials by default in the `urdf-viewer` element.

### CODE REVIEW

**Comment by ipa-jfh** [comment]
> Use cors and same-origin credentials by default in the urdf-viewer element.

Great, the `cors` option is doing the trick that I need to fetch cross-origin. 
Thank you!
So I would be able to use your new defaults. 


> Expose the ability to set the fetch options through the URDFLoader.load function.

If someone does need to change the credentials one would still need to patch the `urdf-viewer-element.js`, right? On the other hand, I agree that a public access function would be an overkill for this feature.

**Comment by gkjohnson** [comment]
> If someone does need to change the credentials one would still need to patch the `urdf-viewer-element.js`, right? On the other hand, I agree that a public access function would be an overkill for this feature.

Yeah I tried to pick defaults that I thought would accommodate most use cases and were sensible for an element. If there's a use case this doesn't cover then I'd be more than happy to revisit it! 

If this looks good for you then I'll merge it in a bit.

Thanks again for your feedback!

**Comment by ipa-jfh** [comment]
Yes I agree, thank you!

**Comment by gkjohnson** [comment]
Great -- I'll update the npm package later tonight!

**Pull request merged**
